## k： v 的写法
#
##对空格的要求十分严格
#
#
##普通的 key - value
#name: lizhen
#
##对象
#student:
#  name: lizhen
#  age: 3
#
#  #对象的行类写法
#student2: {name: lizhen,age: 3}
#
##数组
#pets:
#  -cat
#  -dog
#  -pig
#
#pets2: [cat,dog,pig]


person:
  name: lizhen
  age: 3
  happy: false
  birthday: 2000/1/1
  maps: {k1: v1,ke: v2}
  lists: [1,2,3,4,5,6]
#  dog:
#    name: lizhen2
#    age: 2

